services:
  app:
    build: ../..
    #image: umajho/bangumi-episode-ratings
    container_name: bangumi-episode-ratings
    ports:
      - "8000:80"
    volumes:
      - data:/data
    environment:
      LOG_FILE_PATH: /data/logs/app.log
      KV_PATH: /data/kv.s3db
      AUTH_ROUTE_MODE: '["off"]'
      API_ROUTE_MODE: '["normal"]'
      ENTRYPOINT_URL: https://localhost:8000
      PORT: 80
      BGM_APP_ID: _
      BGM_APP_SECRET: _
      USER_AGENT_FILE: /run/secrets/USER_AGENT
      BGM_HOMEPAGE_URL: https://bangumi.tv/
      JWT_SIGNING_KEY_JWK_FILE: /run/secrets/JWT_SIGNING_KEY_JWK
      JWT_VERIFYING_KEY_JWK_FILE: /run/secrets/JWT_VERIFYING_KEY_JWK
    secrets:
      - USER_AGENT
      - JWT_SIGNING_KEY_JWK
      - JWT_VERIFYING_KEY_JWK
  
  # see: https://github.com/mattn/litestream-sidecar-example/blob/main/docker-compose.yaml
  litestream:
    image: litestream/litestream:0.3.13
    container_name: bangumi-episode-ratings-litestream
    depends_on:
      - app
    volumes:
      - data:/data
      - ./litestream.yml:/opt/litestream/litestream.yml
    entrypoint: /bin/sh
    command: -c "/usr/local/bin/litestream replicate --config /opt/litestream/litestream.yml"

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

secrets:
  USER_AGENT:
    file: ./secrets/USER_AGENT.txt
  JWT_SIGNING_KEY_JWK:
    file: ./secrets/JWT_SIGNING_KEY_JWK.json
  JWT_VERIFYING_KEY_JWK:
    file: ./secrets/JWT_VERIFYING_KEY_JWK.json